[project]
name = "mypackage"
version = "0.0.1"

[tool.setuptools.packages.find]
where = ["python"]

[build-system]
requires = ["setuptools", "wheel", "toml"]
build-backend = "setuptools.build_meta"

[project.scripts]
myscript00 = "mypackage:_scripts_run"
